import { IndicatorConfig } from '@/types';

export const INDICATOR_CONFIGS: IndicatorConfig[] = [
  // MOMENTUM INDICATORS
  {
    key: 'rsi_high',
    name: 'RSI (14)',
    category: 'momentum',
    valueColumn: 'rsi_14_value',
    extremeColumn: 'rsi_14_extreme',
    direction: 'high',
    title: 'Overbought RSI',
    description: 'Relative Strength Index above 70 indicates overbought conditions',
    thresholds: { overbought: 70, oversold: 30 },
    formatValue: (value: number) => value.toFixed(1),
  },
  {
    key: 'rsi_low',
    name: 'RSI (14)',
    category: 'momentum',
    valueColumn: 'rsi_14_value',
    extremeColumn: 'rsi_14_extreme',
    direction: 'low',
    title: 'Oversold RSI',
    description: 'Relative Strength Index below 30 indicates oversold conditions',
    thresholds: { overbought: 70, oversold: 30 },
    formatValue: (value: number) => value.toFixed(1),
  },
  {
    key: 'macd_high',
    name: 'MACD Z-Score',
    category: 'momentum',
    valueColumn: 'macd_z_score',
    extremeColumn: 'macd_extreme',
    direction: 'high',
    title: 'MACD Bullish',
    description: 'Moving Average Convergence Divergence showing strong bullish momentum',
    thresholds: { strong: 2, weak: -2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'macd_low',
    name: 'MACD Z-Score',
    category: 'momentum',
    valueColumn: 'macd_z_score',
    extremeColumn: 'macd_extreme',
    direction: 'low',
    title: 'MACD Bearish',
    description: 'Moving Average Convergence Divergence showing strong bearish momentum',
    thresholds: { strong: 2, weak: -2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'cci_high',
    name: 'CCI',
    category: 'momentum',
    valueColumn: 'cci',
    direction: 'high',
    title: 'CCI Overbought',
    description: 'Commodity Channel Index above 100 indicates overbought',
    thresholds: { overbought: 100, oversold: -100 },
    formatValue: (value: number) => value.toFixed(1),
  },
  {
    key: 'cci_low',
    name: 'CCI',
    category: 'momentum',
    valueColumn: 'cci',
    direction: 'low',
    title: 'CCI Oversold',
    description: 'Commodity Channel Index below -100 indicates oversold',
    thresholds: { overbought: 100, oversold: -100 },
    formatValue: (value: number) => value.toFixed(1),
  },
  {
    key: 'stoch_rsi_high',
    name: 'Stochastic RSI',
    category: 'momentum',
    valueColumn: 'stoch_rsi',
    direction: 'high',
    title: 'Stoch RSI Overbought',
    description: 'Stochastic RSI above 0.8 indicates overbought momentum',
    thresholds: { overbought: 0.8, oversold: 0.2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'stoch_rsi_low',
    name: 'Stochastic RSI',
    category: 'momentum',
    valueColumn: 'stoch_rsi',
    direction: 'low',
    title: 'Stoch RSI Oversold',
    description: 'Stochastic RSI below 0.2 indicates oversold momentum',
    thresholds: { overbought: 0.8, oversold: 0.2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'stochastic_high',
    name: 'Stochastic',
    category: 'momentum',
    valueColumn: 'stochastic',
    direction: 'high',
    title: 'Stochastic Overbought',
    description: 'Stochastic oscillator above 80 indicates overbought',
    thresholds: { overbought: 80, oversold: 20 },
    formatValue: (value: number) => value.toFixed(1),
  },
  {
    key: 'stochastic_low',
    name: 'Stochastic',
    category: 'momentum',
    valueColumn: 'stochastic',
    direction: 'low',
    title: 'Stochastic Oversold',
    description: 'Stochastic oscillator below 20 indicates oversold',
    thresholds: { overbought: 80, oversold: 20 },
    formatValue: (value: number) => value.toFixed(1),
  },

  // TREND INDICATORS
  {
    key: 'adx_high',
    name: 'ADX (14)',
    category: 'trend',
    valueColumn: 'adx_14_value',
    extremeColumn: 'adx_14_extreme',
    direction: 'high',
    title: 'Strongest Trends (ADX)',
    description: 'Average Directional Index above 25 indicates strong trend',
    thresholds: { strong: 25, weak: 20 },
    formatValue: (value: number) => value.toFixed(1),
  },
  {
    key: 'sma_high',
    name: 'SMA',
    category: 'trend',
    valueColumn: 'sma_normalized',
    direction: 'high',
    title: 'Above SMA (Uptrend)',
    description: 'Price significantly above Simple Moving Average',
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'sma_low',
    name: 'SMA',
    category: 'trend',
    valueColumn: 'sma_normalized',
    direction: 'low',
    title: 'Below SMA (Downtrend)',
    description: 'Price significantly below Simple Moving Average',
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'slope_high',
    name: 'Price Slope',
    category: 'trend',
    valueColumn: 'slope_normalized',
    direction: 'high',
    title: 'Steepest Uptrend',
    description: 'Stocks with the steepest positive price slope',
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'slope_low',
    name: 'Price Slope',
    category: 'trend',
    valueColumn: 'slope_normalized',
    direction: 'low',
    title: 'Steepest Downtrend',
    description: 'Stocks with the steepest negative price slope',
    formatValue: (value: number) => value.toFixed(3),
  },

  // VOLUME INDICATORS
  {
    key: 'cmf_high',
    name: 'CMF (20)',
    category: 'volume',
    valueColumn: 'cmf_20_value',
    extremeColumn: 'cmf_20_extreme',
    direction: 'high',
    title: 'Money Flow In (CMF)',
    description: 'Chaikin Money Flow shows strong buying pressure',
    thresholds: { strong: 0.2, weak: -0.2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'cmf_low',
    name: 'CMF (20)',
    category: 'volume',
    valueColumn: 'cmf_20_value',
    extremeColumn: 'cmf_20_extreme',
    direction: 'low',
    title: 'Money Flow Out (CMF)',
    description: 'Chaikin Money Flow shows strong selling pressure',
    thresholds: { strong: 0.2, weak: -0.2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'avgvol_high',
    name: 'Avg Volume',
    category: 'volume',
    valueColumn: 'avgvol_normalized',
    direction: 'high',
    title: 'Highest Volume',
    description: 'Stocks with unusually high average volume',
    formatValue: (value: number) => value.toFixed(2),
  },
  {
    key: 'avgvolccy_high',
    name: 'Volume Currency',
    category: 'volume',
    valueColumn: 'avgvolccy_normalized',
    direction: 'high',
    title: 'Highest Value Traded',
    description: 'Stocks with highest average volume in currency terms',
    formatValue: (value: number) => value.toFixed(2),
  },

  // VOLATILITY INDICATORS
  {
    key: 'bollinger_high',
    name: 'Bollinger Bands',
    category: 'volatility',
    valueColumn: 'bollinger_z_score',
    extremeColumn: 'bollinger_z_extreme',
    direction: 'high',
    title: 'Bollinger Upper Band',
    description: 'Price at or above upper Bollinger Band (high volatility)',
    thresholds: { strong: 2, weak: -2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'bollinger_low',
    name: 'Bollinger Bands',
    category: 'volatility',
    valueColumn: 'bollinger_z_score',
    extremeColumn: 'bollinger_z_extreme',
    direction: 'low',
    title: 'Bollinger Lower Band',
    description: 'Price at or below lower Bollinger Band (volatility compression)',
    thresholds: { strong: 2, weak: -2 },
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'atr_high',
    name: 'ATR',
    category: 'volatility',
    valueColumn: 'atr_normalized',
    direction: 'high',
    title: 'Highest Volatility (ATR)',
    description: 'Average True Range showing highest price volatility',
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'stddev_high',
    name: 'Standard Deviation',
    category: 'volatility',
    valueColumn: 'stddev_normalized',
    direction: 'high',
    title: 'High Standard Deviation',
    description: 'Stocks with highest price standard deviation',
    formatValue: (value: number) => value.toFixed(3),
  },
  {
    key: 'beta_high',
    name: 'Beta',
    category: 'volatility',
    valueColumn: 'beta',
    direction: 'high',
    title: 'High Beta Stocks',
    description: 'Stocks with highest beta (most volatile relative to market)',
    thresholds: { strong: 1.5, weak: 0.5 },
    formatValue: (value: number) => value.toFixed(2),
  },
  {
    key: 'beta_low',
    name: 'Beta',
    category: 'volatility',
    valueColumn: 'beta',
    direction: 'low',
    title: 'Low Beta Stocks',
    description: 'Stocks with lowest beta (least volatile, defensive)',
    thresholds: { strong: 1.5, weak: 0.5 },
    formatValue: (value: number) => value.toFixed(2),
  },
];

export const INDICATOR_CATEGORIES = [
  { value: 'all', label: 'All Indicators' },
  { value: 'momentum', label: 'Momentum' },
  { value: 'trend', label: 'Trend' },
  { value: 'volume', label: 'Volume' },
  { value: 'volatility', label: 'Volatility' },
] as const;

export const TIME_RANGES = [
  { value: '1D', label: '1 Day' },
  { value: '1W', label: '1 Week' },
  { value: '1M', label: '1 Month' },
  { value: '3M', label: '3 Months' },
  { value: '6M', label: '6 Months' },
  { value: '1Y', label: '1 Year' },
  { value: 'All', label: 'All Time' },
] as const;

export const EXCHANGES = [
  { value: 'ALL', label: 'All Exchanges' },
  { value: 'NSE', label: 'NSE' },
  { value: 'US', label: 'US' },
] as const;
